const knownSkills = [
  ".NET",
  "ABAP",
  "Active Directory",
  "Ada",
  "Adobe XD",
  "Agile",
  "AI",
  "Airflow",
  "Alpine.js",
  "Android",
  "Android Studio",
  "Angular",
  "Ansible",
  "Apache",
  "Apache Kafka",
  "Apache Spark",
  "API Testing",
  "Appium",
  "ASP.NET",
  "Assembly",
  "Astro",
  "Aurelia",
  "Auth0",
  "Automation Testing",
  "AWS",
  "Azure",
  "Azure DevOps",
  "Babel",
  "Backup and Recovery",
  "Backbone.js",
  "Bash",
  "Big Data",
  "Bitbucket",
  "Blazor",
  "Blockchain",
  "Bootstrap",
  "Business Intelligence",
  "C",
  "C#",
  "C++",
  "Cassandra",
  "Celery",
  "Chef",
  "CI/CD",
  "Cisco",
  "Cloud Computing",
  "Cloudflare",
  "Clojure",
  "CocoaPods",
  "CodeIgniter",
  "Computer Vision",
  "Confluence",
  "Contentful",
  "Cordova",
  "Couchbase",
  "CouchDB",
  "CSS",
  "Cybersecurity",
  "Cypress",
  "D3.js",
  "Dart",
  "Data Analysis",
  "Data Engineering",
  "Data Mining",
  "Data Science",
  "Data Visualization",
  "Databricks",
  "Deep Learning",
  "Deno",
  "DevOps",
  "Django",
  "DNS",
  "Docker",
  "Drupal",
  "DynamoDB",
  "Elasticsearch",
  "Electron",
  "Elixir",
  "Ember.js",
  "Entity Framework",
  "ERP",
  "React",
  "React Native",
  "Node.js",
  "Express",
  "Express.js",
  "FastAPI",
  "Figma",
  "Firebase",
  "Firewall",
  "Flask",
  "Flutter",
  "Fortinet",
  "Fortran",
  "GCP",
  "Git",
  "GitHub",
  "GitLab",
  "Go",
  "Golang",
  "Google Cloud",
  "Gradle",
  "Grafana",
  "GraphQL",
  "Groovy",
  "Hadoop",
  "Haskell",
  "Hibernate",
  "HTML",
  "IaaS",
  "IIS",
  "Incident Response",
  "Information Security",
  "IntelliJ IDEA",
  "Internet of Things",
  "IoT",
  "iOS",
  "ITIL",
  "J2EE",
  "Java",
  "JavaFX",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Jira",
  "Joomla",
  "jQuery",
  "JSON",
  "JUnit",
  "Keras",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Linux",
  "Load Balancing",
  "LAN",
  "Lua",
  "Machine Learning",
  "MariaDB",
  "Material UI",
  "Matlab",
  "Maven",
  "Microsoft 365",
  "Microsoft SQL Server",
  "Microservices",
  "Mocha",
  "MongoDB",
  "Mongoose",
  "MySQL",
  "NestJS",
  "Network Administration",
  "Network Security",
  "Networking",
  "Next.js",
  "Nginx",
  "NLP",
  "NoSQL",
  "Nuxt.js",
  "OAuth",
  "Objective-C",
  "OpenCV",
  "OpenShift",
  "Oracle",
  "PaaS",
  "Palo Alto",
  "Pandas",
  "Penetration Testing",
  "Perl",
  "PHP",
  "Playwright",
  "PostgreSQL",
  "Power BI",
  "PowerShell",
  "Prisma",
  "Prometheus",
  "Prolog",
  "Puppet",
  "PyTorch",
  "Python",
  "QA",
  "RabbitMQ",
  "R",
  "React.js",
  "Redis",
  "Redux",
  "REST API",
  "Robotic Process Automation",
  "RPA",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "SaaS",
  "Salesforce",
  "SAP",
  "Sass",
  "Scala",
  "Scrum",
  "Security",
  "Selenium",
  "Shell Scripting",
  "Shopify",
  "SIEM",
  "Snowflake",
  "SOAP",
  "Software Testing",
  "Solidity",
  "Spark",
  "Spring",
  "Spring Boot",
  "SQL",
  "SQLite",
  "SRE",
  "SSIS",
  "Swift",
  "Symfony",
  "System Administration",
  "Tailwind CSS",
  "TensorFlow",
  "Terraform",
  "Three.js",
  "Tomcat",
  "Troubleshooting",
  "TCP/IP",
  "TypeScript",
  "Ubuntu",
  "UI/UX",
  "Unity",
  "Unix",
  "Unreal Engine",
  "VBA",
  "VB.NET",
  "Virtualization",
  "Visual Basic",
  "Visual Studio",
  "Visual Studio Code",
  "Vite",
  "VMware",
  "VPN",
  "Vue.js",
  "WAN",
  "Webpack",
  "Windows Server",
  "WooCommerce",
  "WordPress",
  "XML",
  "YAML",
  "Yii",
  "Zend",
  "Zero Trust",
];

const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const extractSkillsFromText = (text) => {
  return knownSkills.filter((skill) => {
    const skillPattern = new RegExp(
      `(^|[^a-z0-9+#.])${escapeRegExp(skill)}($|[^a-z0-9+#.])`,
      "i"
    );

    return skillPattern.test(text);
  });
};

module.exports = {
  extractSkillsFromText,
};
